version: '3.8'

services:
  mysql:
    container_name: video_admin_mysql
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: video_admin
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - video_admin_network

  rabbitmq:
    container_name: video_admin_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWAGEQDALODSK
      - RABBITMQ_DEFAULT_USER=video_admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - video_admin_network

networks:
  video_admin_network: