amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

mysql:
  username: ${DATABASE_USERNAME:root}
  password: ${DATABASE_PASSWORD:root}
  schema: ${DATABASE_SCHEMA:video_admin}
  url: ${DATABASE_URL:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
