server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4 # Number of IO threads (default is 2 * number of available processors)

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
        "[hibernate.generate_statistics]": false
        "[hibernate.connection.provider_disables_autocommit]": true
