spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:mem:video_admin_test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2