mysql:
  username: root
  password: root
  schema: video_admin
  url: localhost:${mysql.port}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration