mysql:
  username: root
  password: root
  schema: video_admin
  url: localhost:3306

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2 # Number of IO threads (default is 2 * number of available processors)