server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4 # Number of IO threads (default is 2 * number of available processors)